name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: testcgg  # Set this to the name of your Azure Web App
  AZURE_TENANT_ID: 0f58c4d1-fbb2-45b8-a0a2-63f1dccdceea  # Azure Tenant ID
  AZURE_APP_ID: d43ff5aa-b3cb-41c8-9f82-3c73cdd44fb8  # Application (Client) ID
  AZURE_SUBSCRIPTION_ID: 5a867e72-92e0-4b09-8f61-0c7f00af0f6d  # Azure Subscription ID

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log in to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .  # Path to your app's Dockerfile
          file: ./Dockerfile  # Path to your Dockerfile
          push: true  # Automatically push to Docker Hub
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nodejsapp:${{ github.sha }}  # Tag with SHA
          cache-from: type=gha  # Use GitHub cache to speed up builds
          cache-to: type=gha,mode=max

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_APP_ID }}  # Set this to your Azure App ID
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}  # Set this to your Azure Client Secret
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Set this to your Azure Tenant ID

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nodejsapp:${{ github.sha }}'

      - name: Azure logout
        run: |
          az logout
